/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CountryPageNameLazyImport = createFileRoute('/CountryPage/$name')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CountryPageNameLazyRoute = CountryPageNameLazyImport.update({
  id: '/CountryPage/$name',
  path: '/CountryPage/$name',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/CountryPage/$name.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/CountryPage/$name': {
      id: '/CountryPage/$name'
      path: '/CountryPage/$name'
      fullPath: '/CountryPage/$name'
      preLoaderRoute: typeof CountryPageNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/CountryPage/$name': typeof CountryPageNameLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/CountryPage/$name': typeof CountryPageNameLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/CountryPage/$name': typeof CountryPageNameLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CountryPage/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CountryPage/$name'
  id: '__root__' | '/' | '/CountryPage/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CountryPageNameLazyRoute: typeof CountryPageNameLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CountryPageNameLazyRoute: CountryPageNameLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/CountryPage/$name"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/CountryPage/$name": {
      "filePath": "CountryPage/$name.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
