export const storeProducts = [
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-waffle-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-waffle-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-waffle-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-waffle-desktop.jpg',
    },
    name: 'Waffle with Berries',
    category: 'Waffle',
    price: 6.5,
    id: 1,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-creme-brulee-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-creme-brulee-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-creme-brulee-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-creme-brulee-desktop.jpg',
    },
    name: 'Vanilla Bean Crème Brûlée',
    category: 'Crème Brûlée',
    price: 7.0,
    id: 2,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-macaron-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-macaron-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-macaron-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-macaron-desktop.jpg',
    },
    name: 'Macaron Mix of Five',
    category: 'Macaron',
    price: 8.0,
    id: 3,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-tiramisu-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-tiramisu-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-tiramisu-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-tiramisu-desktop.jpg',
    },
    name: 'Classic Tiramisu',
    category: 'Tiramisu',
    price: 5.5,
    id: 4,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-baklava-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-baklava-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-baklava-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-baklava-desktop.jpg',
    },
    name: 'Pistachio Baklava',
    category: 'Baklava',
    price: 4.0,
    id: 5,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-meringue-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-meringue-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-meringue-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-meringue-desktop.jpg',
    },
    name: 'Lemon Meringue Pie',
    category: 'Pie',
    price: 5.0,
    id: 6,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-cake-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-cake-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-cake-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-cake-desktop.jpg',
    },
    name: 'Red Velvet Cake',
    category: 'Cake',
    price: 4.5,
    id: 7,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-brownie-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-brownie-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-brownie-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-brownie-desktop.jpg',
    },
    name: 'Salted Caramel Brownie',
    category: 'Brownie',
    price: 4.5,
    id: 8,
  },
  {
    image: {
      thumbnail: '/src/assets/images/thumbnail/image-panna-cotta-thumbnail.jpg',
      mobile: '/src/assets/images/mobile/image-panna-cotta-mobile.jpg',
      tablet: '/src/assets/images/tablet/image-panna-cotta-tablet.jpg',
      desktop: '/src/assets/images/desktop/image-panna-cotta-desktop.jpg',
    },
    name: 'Vanilla Panna Cotta',
    category: 'Panna Cotta',
    price: 6.5,
    id: 9,
  },
];
